services:
  db:
    build: d:/REDCAP_TOUR/proj/don_bulkup/docker/postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ppogre123!
    volumes:
      - postgres_data:/var/lib/postgresql/18/main

  app:
    build: d:/REDCAP_TOUR/proj/don_bulkup/docker/python
    container_name: python
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://kbs:kbs123!@db:5432/don_bulkup

volumes:
  postgres_data: